#!/usr/bin/env node
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawn } from "node:child_process";

const sourceUrl = "https://api-docs.render.com/openapi/render-public-api-1.json";
const target = resolve("src/Api/schema.ts");
const sha256 = (value) => createHash("sha256").update(value).digest("hex");
const run = (command, args) => new Promise((resolveRun, reject) => {
  const child = spawn(command, args, { stdio: "inherit" });
  child.once("error", reject);
  child.once("exit", (code) => code === 0 ? resolveRun() : reject(new Error(`generator exited with ${code}`)));
});

const dir = await mkdtemp(join(tmpdir(), "alchemy-render-api-"));
try {
  // Network access occurs only in this explicitly invoked script, never build/prepack.
  const response = await fetch(sourceUrl);
  if (!response.ok) throw new Error(`failed to fetch Render OpenAPI schema: ${response.status}`);
  const source = Buffer.from(await response.arrayBuffer());
  const input = join(dir, "render-openapi.json");
  const output = join(dir, "schema.ts");
  await writeFile(input, source);
  await run(process.execPath, [resolve("node_modules/openapi-typescript/bin/cli.js"), input, "-o", output]);
  const declarations = (await readFile(output, "utf8"))
    .replace(/\r\n/g, "\n")
    .replace(/^\/\*\*[\s\S]*?auto-generated by openapi-typescript[\s\S]*?\*\/\n+/i, "");
  const header = `// @ts-nocheck -- Render's upstream schema contains recursive JSON-pointer aliases\n/**\n * Generated by openapi-typescript 7.13.0. Do not edit.\n * Source: ${sourceUrl}\n * Source SHA-256: ${sha256(source)}\n * Declarations SHA-256: ${sha256(declarations)}\n * Deterministic metadata intentionally omits a timestamp.\n */\n\n`;
  await writeFile(target, header + declarations);
  console.log(`wrote ${target}`);
} finally {
  await rm(dir, { recursive: true, force: true });
}
